# -*- coding: utf-8 -*-
S = []

S.append(dict(t="section", era="meta", part="VI", kicker="Part VI",
    title="Engineering Reality",
    lead="The same eighteen years, read again — this time from the source files rather than the papers.",
    body={"items": ["The organising question", "Repositories, at pinned commits", "The prior, era by era, in code",
                    "Frameworks, configuration, data pipelines", "Losses and pre-trained weights",
                    "What we measured, and what broke"]},
    cite="brief §5 · Practical Deep-Dive (Engineering Reality)",
    notes="State the framing before any code appears. Without it this part degenerates into a tour of repositories, which is precisely the failure mode the brief warns against."))

S.append(dict(t="table", era="meta", part="VI", kicker="58 · The organising question",
    title="Open the source file. Where is the prior?",
    lead="Asked of one codebase per era, that single question produces a coherent engineering history instead of a set of disconnected repository summaries — and it answers, in passing, all four things the brief demands of a code deep-dive: structure, framework, data pipeline, and use of pre-trained weights.",
    body={"cols": ["Era", "Open the file, and you find…", "What ships to a user", "Test-time cost"],
          "align": "llll",
          "rows": [
            ["Classical DIP", "A `while` loop and a hand-tuned `weight` argument", "An algorithm", "An optimisation, per image"],
            ["Deep CNN, 2017", "A list comprehension of convolution layers", "A `.pth` file", "One forward pass"],
            ["Data branch, 2018–2025", "The supervision — what goes in and what it is scored against. **The network stops changing.**", "A `.pth`, plus ~50 gradient steps per image", "A short optimisation, per image"],
            ["Architecture branch, 2022–2024", "A new operator replacing the 3×3 convolution", "A `.pth` and a YAML config", "One forward pass"],
          ]},
    foot="**The arc in one sentence.** The prior moved out of the algorithm and into the weights — and then, on the data branch, partly back out of the weights and into a per-image optimisation that needs no clean data at all.",
    cite="reading — the framing used throughout Stage 2",
    notes="If you deliver one sentence from Part VI in the condensed presentation, deliver the foot note. It is the whole of Stage 2 compressed."))

S.append(dict(t="table", era="meta", part="VI", kicker="59 · Provenance",
    title="Repositories inspected, at pinned commits",
    lead="Every code claim in this part was read from these trees at these commits. Pinning matters: `main` moves, and a claim about a moving branch is not reproducible.",
    body={"cols": ["Model", "Repository", "Commit", "Framework"],
          "align": "llll",
          "rows": [
            ["Total variation (classical exemplar)", "`scikit-image` 0.26.0, from PyPI", "released version", "NumPy"],
            ["DnCNN", "`github.com/cszn/DnCNN`", "`e93b278…`", "MatConvNet (MATLAB) + PyTorch port"],
            ["DnCNN, SCUNet weights", "`github.com/cszn/KAIR`", "`fc1732f…`", "PyTorch"],
            ["Noise2Noise", "`github.com/NVlabs/noise2noise`", "`7355519…`", "**TensorFlow**"],
            ["Restormer", "`github.com/swz30/Restormer`", "`68dc6ac…`", "PyTorch + BasicSR"],
            ["NAFNet", "`github.com/megvii-research/NAFNet`", "`2b4af71…`", "PyTorch + BasicSR"],
            ["SCUNet", "`github.com/cszn/SCUNet`", "`52e440a…`", "PyTorch"],
            ["MambaIR", "`github.com/csguoh/MambaIR`", "`33d7b34…`", "PyTorch + `mamba_ssm` CUDA ext."],
            ["P2N+", "`github.com/Li-Tong-621/P2N-plus`", "`8a117db…`", "PyTorch"],
          ]},
    foot="**Two provenance notes that matter and are not in any paper.** ZS-N2N has no GitHub repository at all — it was released solely as a Colab notebook. WNNM has only a third-party mirror, with no README and no licence. The availability of reference code is itself uneven across the field, and it is an obstacle to reproduction that citation counts do not show.",
    cite="measured — repositories cloned and read, Stage 2",
    notes="If asked why DnCNN's own repo is not the main exhibit: because it is MATLAB, and the brief scopes the deep-dive to modern approaches. KAIR is the PyTorch reference the field actually uses."))

S.append(dict(t="code", era="classical", part="VI", kicker="60 · Era I in code",
    title="The classical prior is a while loop you can read",
    lead="`scikit-image 0.26.0`, `restoration/_denoise.py`, `denoise_tv_chambolle`. The structure below is the Chambolle projection algorithm as implemented there.",
    body={"lang": "python", "file": "skimage/restoration/_denoise.py — structure",
     "lines": [
        "def _denoise_tv_chambolle_nd(image, weight=0.1, eps=2.e-4, max_num_iter=200):",
        "    p    = np.zeros((image.ndim,) + image.shape, dtype=...)   # dual variable",
        "    g    = np.zeros_like(p)",
        "    i = 0",
        "    while i < max_num_iter:                    # ← the entire 'training'",
        "        ...",
        "        d = -p.sum(0)                          # divergence of the dual field",
        "        out = image + d",
        "        E = (d ** 2).sum()",
        "        ...",
        "        norm = np.sqrt((g ** 2).sum(axis=0))[np.newaxis, ...]",
        "        E += weight * norm.sum()               # ← λ·Φ(x), the prior, one line",
        "        tau = 1. / (2. * image.ndim)",
        "        norm = norm * tau / weight",
        "        norm += 1.",
        "        p = p - tau * g",
        "        p /= norm                              # projection onto the dual ball",
        "        E /= float(image.size)",
        "        if i == 0: E_init = E; E_previous = E",
        "        else:",
        "            if np.abs(E_previous - E) < eps * E_init:  break   # ← convergence",
        "            else: E_previous = E",
        "        i += 1",
        "    return out",
     ],
     "bullets": [
        "**Four things are visible on one screen, and they characterise the entire era.** (1) `weight` *is* λ — the prior's strength is a function argument a human passes. (2) `norm.sum()` *is* Φ(x) = ‖∇x‖₁ — the prior itself, in one line of arithmetic you can read and differentiate by hand. (3) The `while` loop is the test-time optimisation. (4) The `break` on relative energy change is the stopping criterion.",
        "**Nothing persists.** There is no state, no file, no checkpoint. Call the function on a second image and every one of these iterations runs again from scratch. That is bottleneck 1, expressed as control flow.",
        "**The contrast to hold in mind for the next slide.** Here the prior is *readable and untrainable*. In three slides it becomes *trainable and unreadable*. That trade is the whole of the deep era.",
     ]},
    cite="measured — `scikit-image` 0.26.0, installed from PyPI and read",
    notes="This is the classical exhibit precisely because it is so small. One screen of NumPy against one screen of PyTorch is a sharper argument than any prose comparison."))

S.append(dict(t="code", era="deepcnn", part="VI", kicker="61 · Era II in code",
    title="DnCNN is a list comprehension",
    lead="`cszn/KAIR`, `models/network_dncnn.py`. The reference PyTorch implementation, by DnCNN's own first author. Verbatim.",
    body={"lang": "python", "file": "KAIR/models/network_dncnn.py",
     "lines": [
        "class DnCNN(nn.Module):",
        "    def __init__(self, in_nc=1, out_nc=1, nc=64, nb=17, act_mode='BR'):",
        "        super(DnCNN, self).__init__()",
        "        assert 'R' in act_mode or 'L' in act_mode",
        "        bias = True",
        "",
        "        m_head = B.conv(in_nc, nc, mode='C'+act_mode[-1], bias=bias)",
        "        m_body = [B.conv(nc, nc, mode='C'+act_mode, bias=bias)",
        "                  for _ in range(nb-2)]                    # ← the whole network",
        "        m_tail = B.conv(nc, out_nc, mode='C', bias=bias)",
        "",
        "        self.model = B.sequential(m_head, *m_body, m_tail)",
        "",
        "    def forward(self, x):",
        "        n = self.model(x)",
        "        return x-n                                          # ← residual learning",
     ],
     "bullets": [
        "**The architecture is one line.** `m_body` is a list comprehension of `nb-2` identical blocks. The three layer types from slide 29 are literally `m_head`, `m_body`, `m_tail`. There is no architectural cleverness to read because there is none in the paper.",
        "**`mode='C'+act_mode` is the whole layer grammar.** `'CBR'` = Convolution → BatchNorm → ReLU for the body; `'CR'` = Convolution → ReLU for the head; `'C'` = Convolution alone for the tail. Exactly the paper's Fig. 1, encoded as a three-character string.",
        "**`return x-n` is the paper's central idea, in eight characters.** Note the subtlety: the *paper's network* outputs v̂, and the subtraction happens outside. KAIR folds the subtraction inside `forward`, so the module returns the clean image. The residual mapping is still what the weights learn — only the boundary of the module moved.",
        "**Where is the prior?** Nowhere in this file. It is in the `.pth` checkpoint this class will load. The file describes a *shape*; the prior is the tensor poured into it. This is the moment the prior stops being readable.",
     ]},
    cite="measured — `cszn/KAIR`, `models/network_dncnn.py`, verbatim",
    notes="Best single slide for the 'do you understand the code' question. Put the TV while-loop and this side by side mentally: the prior moved from line 11 of one file into a binary file that is not in the repository at all."))

S.append(dict(t="two", era="data", part="VI", kicker="62 · The data branch in code",
    title="Noise2Noise is an if-statement, and P2N is three forward passes",
    lead="The strongest evidence that the data branch is a supervision story rather than an architecture story is that its code contains almost no architecture.",
    body={"left": {"h": "Noise2Noise, 2018 — NVlabs", "bullets": [
        "The repository is **TensorFlow** — the last major denoiser released outside PyTorch. Everything in Part V and everything after 2019 in Part IV is PyTorch. The migration is visible as a single dated boundary in the field's source history.",
        "The change from supervised training is structurally one branch: the target tensor is either the clean image or a second noisy image. The network, the optimiser, the schedule and the loss are untouched.",
        "**The theorem from slide 39 costs one conditional.** That asymmetry — a substantial statistical result, a trivial code change — is the whole reason the paper landed.",
    ]},
     "right": {"h": "P2N+, 2025 — Li-Tong-621", "bullets": [
        "The network class is named **`UNet_n2n_un`** and its channel widths match the 2018 Noise2Noise U-Net exactly. Seven years later, the backbone is literally named after its predecessor.",
        "`noise_estimation_loss` does not merely score an output. It **constructs the inputs**: run the model on y, estimate the noise, add it back with `+` and with `−` to build y⁺ and y⁻, then run the model twice more and compare the two *outputs* to each other.",
        "**Three forward passes per training step**, and the second and third operate on tensors that did not exist before the first. This is why calling P2N 'a new loss function' is wrong — a loss scores a fixed prediction against a fixed target.",
        "One function in this repository implements **all** the competing self-supervised paradigms behind a `--mode` flag — N2V, N2N, and the RDC/DCS branches. The whole data branch fits in one file.",
     ]},
    },
    foot="**A caveat we found in the code and would not overstate.** Two of those `--mode` branches feed RDC-constructed data to Noise2Void and Noise2Noise. The paper itself states this data is unsuitable for them, because the noise in RDC-constructed images is **correlated**, which collapses their training. Those branches are a documented negative result, not a fair comparison — and reading the flag table without reading the paper would lead you to the opposite conclusion.",
    cite="measured — `NVlabs/noise2noise` commit 7355519; `Li-Tong-621/P2N-plus` commit 8a117db · P2N25 on RDC data unsuitability",
    notes="The correlated-noise caveat is a genuine rigour point and was a correction we made during Stage 2. It shows the code and the paper being read against each other."))

S.append(dict(t="code", era="arch", part="VI", kicker="63 · Where Restormer's attention is linear",
    title="One `rearrange` is the difference between O(HW·HW) and O(C·C)",
    lead="`swz30/Restormer`, `basicsr/models/archs/restormer_arch.py`, `Attention.forward`. Verbatim. The claim of linear complexity is not in a comment — it is in the tensor layout.",
    body={"lang": "python", "file": "Restormer/basicsr/models/archs/restormer_arch.py",
     "lines": [
        "def forward(self, x):",
        "    b,c,h,w = x.shape",
        "",
        "    qkv = self.qkv_dwconv(self.qkv(x))     # 1x1 conv, then 3x3 depth-wise",
        "    q,k,v = qkv.chunk(3, dim=1)",
        "",
        "    q = rearrange(q, 'b (head c) h w -> b head c (h w)', head=self.num_heads)",
        "    k = rearrange(k, 'b (head c) h w -> b head c (h w)', head=self.num_heads)",
        "    v = rearrange(v, 'b (head c) h w -> b head c (h w)', head=self.num_heads)",
        "",
        "    q = torch.nn.functional.normalize(q, dim=-1)",
        "    k = torch.nn.functional.normalize(k, dim=-1)",
        "",
        "    attn = (q @ k.transpose(-2, -1)) * self.temperature   # ← (C/head) x (C/head)",
        "    attn = attn.softmax(dim=-1)",
        "",
        "    out = (attn @ v)",
        "    out = rearrange(out, 'b head c (h w) -> b (head c) h w',",
        "                    head=self.num_heads, h=h, w=w)",
        "    return self.project_out(out)",
     ],
     "bullets": [
        "**Read the einops pattern.** `'b (head c) h w -> b head c (h w)'` puts **pixels on the last axis and channels second-to-last**. In standard spatial attention it is the other way round.",
        "**Therefore `q @ k.transpose(-2,-1)` has shape (C/head) × (C/head)**, not (HW) × (HW). At level 1 with dim = 48 and 1 head, that is a 48×48 matrix regardless of whether the image is 256×256 or 4000×3000. The paper's linear-complexity claim is exactly this line.",
        "**`F.normalize` along the pixel axis** makes the product a cosine similarity between channels — the cross-covariance the paper describes — and `self.temperature` is a learned per-head scale replacing the fixed 1/√d_k.",
        "**`qkv_dwconv` is the locality the paper insists on**, and the ablation on slide 50 measures its worth at 0.15 dB. Removing one `groups=dim*3` convolution costs more than most architectural papers gain.",
        "**Why it is nonetheless slow on CPU.** Three `rearrange` calls force tensor-layout changes, and attention matmuls are poorly served by a CPU backend. Measured: **10.44 s at 256×256**, the slowest model we ran. `[measured]`",
     ]},
    cite="measured — `swz30/Restormer`, `restormer_arch.py`, `Attention.forward`, verbatim",
    notes="'Show me where the attention is actually linear' is the most likely code question in the whole defence. Be able to point at the rearrange pattern and say which axis the pixels are on."))

S.append(dict(t="code", era="arch", part="VI", kicker="64 · NAFNet's simplifications, in four lines",
    title="SimpleGate and SCA are smaller than their descriptions",
    lead="`megvii-research/NAFNet`, `basicsr/models/archs/NAFNet_arch.py`. Verbatim. The paper spends two pages deriving these; the implementation is four lines and a `Sequential`.",
    body={"lang": "python", "file": "NAFNet/basicsr/models/archs/NAFNet_arch.py",
     "lines": [
        "class SimpleGate(nn.Module):",
        "    def forward(self, x):",
        "        x1, x2 = x.chunk(2, dim=1)",
        "        return x1 * x2                  # ← replaces GELU entirely",
        "",
        "# Simplified Channel Attention, inside NAFBlock.__init__:",
        "self.sca = nn.Sequential(",
        "    nn.AdaptiveAvgPool2d(1),",
        "    nn.Conv2d(dw_channel // 2, dw_channel // 2, kernel_size=1, bias=True),",
        ")                                       # ← no ReLU, no Sigmoid",
        "",
        "# NAFBlock.forward, first half:",
        "x = self.norm1(inp)",
        "x = self.conv1(x)                       # 1x1, expand",
        "x = self.conv2(x)                       # 3x3 depth-wise (groups=dw_channel)",
        "x = self.sg(x)                          # SimpleGate: halves the channels",
        "x = x * self.sca(x)                     # SCA",
        "x = self.conv3(x)                       # 1x1, project back",
        "y = inp + x * self.beta                 # learned residual scale",
     ],
     "bullets": [
        "**`x.chunk(2, dim=1)` then `x1 * x2`.** Compare with GELU's implementation: `0.5x(1+tanh[√(2/π)(x+0.044715x³)])`. The paper's claim that the activation is unnecessary is not rhetoric — the replacement is genuinely a channel split and a multiply.",
        "**`self.sca` contains no nonlinearity at all.** Compare to standard channel attention, which is pool → 1×1 → ReLU → 1×1 → Sigmoid. Two activations removed, and slide 53 measures the result as **+0.03 dB**, not a loss.",
        "**`self.beta` and `self.gamma` are learned scalars initialised to zero** — `skip-init`, which means the block starts as an identity and training decides how much of it to switch on. This is a stability device, not an architectural claim, and it does not appear in the paper's block diagram.",
        "**Where the parameters live.** Width doubles per level, so the 12 middle blocks run at 1024 channels; each `NAFBlock` costs roughly 7c², giving 12 × 7 × 1024² ≈ **88 M of the 116 M total in the bottleneck alone**. `[measured]`",
        "**Why it is fast despite being large.** 1×1 and depth-wise convolutions map onto highly optimised GEMM kernels. Measured: **1.90 s at 256×256 — 5.5× faster than Restormer with 4.4× the parameters.** `[measured]`",
     ]},
    cite="measured — `megvii-research/NAFNet`, `NAFNet_arch.py`, verbatim",
    notes="The beta/gamma skip-init detail is a good one to have: it is in the code, mentioned only briefly in the paper, and shows you read past the block diagram."))

S.append(dict(t="table", era="meta", part="VI", kicker="65 · Frameworks and configuration",
    title="How the field's software stack moved, dated by repository",
    lead="The brief asks what frameworks these models use and how pre-trained weights are used today compared with older manual methods. The answer is best given as a migration with dates attached to actual commits.",
    body={"cols": ["Era", "Framework", "Configuration", "How a model is instantiated"],
          "align": "llll",
          "rows": [
            ["Classical, ≤2014", "MATLAB / C, or NumPy", "Function arguments", "Call a function with tuned constants"],
            ["DnCNN, 2017", "**MatConvNet** (MATLAB)", "Hard-coded in a training script", "Edit the script, rerun"],
            ["Noise2Noise, 2018", "**TensorFlow**", "`argparse` flags", "Command line"],
            ["KAIR, 2018–2024", "PyTorch", "A JSON options file", "Name a model string, options resolve it"],
            ["Restormer / NAFNet, 2022", "PyTorch + **BasicSR**", "**YAML**, resolved by a registry", "`build_network(opt)` reads `type:` from YAML"],
            ["SCUNet, 2023", "PyTorch", "Constructor arguments", "Direct instantiation"],
            ["MambaIR, 2024", "PyTorch + compiled CUDA ext.", "YAML + BasicSR registry", "Requires `mamba_ssm` to import at all"],
            ["P2N+, 2025", "PyTorch", "`argparse`, with a `--mode` flag", "One flag selects the training paradigm"],
          ]},
    foot="**Two observations worth making aloud.** (1) The registry pattern in BasicSR means the *architecture is named by a string in a config file*, so swapping Restormer for NAFNet is a one-line YAML edit — architectures have become interchangeable components. (2) Between 2017 and 2022 the unit of reproducibility moved from *a script you edit* to *a config you version-control*, which is why modern papers can honestly claim exact reproduction.",
    cite="measured — repositories at the commits on slide 59",
    notes="This slide is the direct answer to the brief's framework question. Have the BasicSR registry point ready; it is the strongest single observation here."))

S.append(dict(t="two", era="meta", part="VI", kicker="66 · Data pipelines",
    title="Where the noise is added, and why that choice matters",
    lead="The brief asks how modern data pipelines work. The interesting axis is not the `Dataset` boilerplate — it is *when* the degradation is applied, because that determines what the network can possibly learn.",
    body={"left": {"h": "The two strategies", "bullets": [
        "**Offline.** Generate noisy/clean pairs once, write them to disk, and read them during training. Deterministic and fast, but the network sees each noise realisation many times and can memorise it.",
        "**On-the-fly, in `__getitem__`.** Draw a fresh noise realisation for every sample, every epoch. The network never sees the same corrupted patch twice, which is a powerful implicit regulariser — and it is free.",
        "**DnCNN, 2017:** patches cropped from 400 images, noise added per sample, σ drawn from [0, 55] for the blind model. 128 × 3 000 patches of 50×50.",
        "**SCUNet, 2023:** the entire degradation chain — Gaussian, Poisson, speckle, JPEG, ISP-simulated sensor noise, resizing, with random shuffling and double degradation — is executed **per sample, at load time**. The dataloader is the contribution.",
    ]},
     "right": {"h": "What is in every modern pipeline", "bullets": [
        "**Random crop** to a fixed patch size. 40–50 px in DnCNN; 128 px rising to 384 px in Restormer's progressive schedule; 256 px in NAFNet; 128 px in MambaIR's denoising configuration.",
        "**Geometric augmentation only.** Horizontal and vertical flips, and 90°/180°/270° rotations. Notably absent: colour jitter, cutout, mixup — anything that alters intensity statistics would corrupt the very quantity being estimated.",
        "**Batch size traded against patch size.** Restormer explicitly reduces batch size as patch size grows *to maintain a similar time per optimisation step*.",
        "**Real-noise datasets skip synthesis entirely.** SIDD ships 320 captured noisy/clean scene pairs. There is no noise model in that pipeline — the camera is the noise model.",
    ]},
    },
    foot="**The one line to take away.** In 2017 the data pipeline was infrastructure. By 2023 — in SCUNet, and in the whole data branch of Part IV — the data pipeline *is the method*.",
    cite="DnCNN17 §IV-A · SCUNet23 §3.2 · Restormer22 §4 · MambaIR24 §4.1 · NAFNet22 §5.1",
    notes="'In 2017 the pipeline was infrastructure; by 2023 it is the method' is a line worth memorising. It connects Part VI back to Parts IV and V in one sentence."))

S.append(dict(t="cards", era="meta", part="VI", kicker="67 · Loss functions",
    title="What modern denoisers actually optimise — and what they conspicuously do not",
    lead="The brief asks specifically about the modern loss functions being used. The finding is a negative one and it is more interesting than the positive list.",
    body={"cards": [
        {"tag": "Restormer", "h": "Plain L1", "p": "`L1 loss for 300K iterations`. No perceptual term, no adversarial term. The most-cited restoration Transformer of the decade optimises mean absolute error."},
        {"tag": "NAFNet", "h": "PSNR loss", "p": "The negative of the evaluation metric, computed per image before the batch mean. Optimising the metric directly — honest, and a reminder that the metric is the target."},
        {"tag": "P2N", "h": "Annealed ℓ_r", "p": "An ℓ_r loss with r **decreasing during training** from 2 toward 1.5 or 0 — moving the estimator from the mean toward the median and beyond, as the model's own estimates become trustworthy. `[measured]`"},
        {"tag": "**Absent**", "h": "Perceptual and adversarial losses", "p": "Essentially absent from denoising, in contrast to super-resolution, where SRGAN-style losses are standard. **Reason:** denoising is evaluated by fidelity to a known ground truth, and a GAN that hallucinates plausible texture scores worse even when it looks better. The metric constrains the loss."},
    ]},
    foot="**The honest caveat.** That last card is an inference from what we read across five repositories, not a claim any of these papers makes. It is labelled as a reading, and if a TA challenges it, the correct response is that we observed the absence rather than that a paper asserted it.",
    cite="Restormer22 §4 · NAFNet22 §5.1 · measured — P2N-plus loss code · reading",
    notes="The perceptual-loss absence is a strong observation and an obvious question hook. Do not overclaim it — say 'we observed' and name the five repositories."))

S.append(dict(t="two", era="meta", part="VI", kicker="68 · Pre-trained weights",
    title="The prior became a file you download",
    lead="This is the brief's sharpest comparison: how pre-trained weights are used today versus older manual feature-extraction methods. The contrast is total, and it is best stated in terms of what each era ships.",
    body={"left": {"h": "Then — the classical artefact", "bullets": [
        "**What ships:** an algorithm, plus constants a human chose.",
        "**Reuse:** none. Every image restarts from nothing. Nothing computed on image 1 helps image 2.",
        "**Adaptation to a new domain:** re-derive the prior, or re-tune the constants by hand, and hope.",
        "**Reproducibility:** depends on matching the author's parameter table, which is often in prose rather than code.",
        "**Where the knowledge lives:** in the paper.",
    ]},
     "right": {"h": "Now — the modern artefact", "bullets": [
        "**What ships:** a `.pth` file — a serialised `state_dict`, a dictionary mapping layer names to tensors. Downloaded once, reused indefinitely.",
        "**Loading:** `model.load_state_dict(torch.load(path))`, with `strict=True` by default so a shape mismatch fails loudly rather than silently.",
        "**Distribution:** GitHub Releases, Google Drive links, and increasingly Hugging Face model cards that carry the architecture, the training data, the metrics and the licence as structured metadata.",
        "**Adaptation:** fine-tune, or use the weights as an initialisation — which is precisely what P2N does before its per-image optimisation.",
        "**Where the knowledge lives:** in the tensors. The repository describes only a shape.",
    ]},
    },
    foot="**The consequence that is easy to miss.** Because the weights are a file and the architecture is a string in a YAML, a modern denoiser is *two decoupled artefacts*. You can ship a better checkpoint without touching the code, and swap the architecture without retraining the pipeline. The classical era had no such separation, and that is a large part of why it could not compound.",
    cite="measured — checkpoint loading in KAIR, Restormer, NAFNet, SCUNet · brief §2 on pre-trained weights",
    notes="This is the slide that directly answers a question the brief asks in so many words. Expect it to be asked and answer with the two-artefact framing."))

S.append(dict(t="table", era="meta", part="VI", kicker="69 · A deployment detail no paper reports",
    title="Every model pads — and they all pad differently",
    lead="A U-Net that downsamples k times requires input dimensions divisible by 2ᵏ. Every architecture-branch model solves this with the same pad-then-crop idiom and a different constant, which becomes a real problem the moment two are chained in one pipeline.",
    body={"cols": ["Model", "Required multiple", "Padding mode", "Where"],
          "align": "lrll",
          "rows": [
            ["Restormer", "8", "`reflect`", "`demo.py`"],
            ["NAFNet", "16 — computed as `2 ** len(self.encoders)`", "zero (default `F.pad`)", "`NAFNet_arch.check_image_size`"],
            ["P2N+", "32", "`reflect`", "`test.py`"],
            ["SCUNet", "64 — `int(np.ceil(h/64)*64-h)`", "`nn.ReplicationPad2d`", "`network_scunet.forward`"],
          ]},
    foot="**A factor of eight separates the extremes, and the padding *mode* differs too** — zero padding injects a hard artificial edge, reflection and replication do not. Feed a 1000×1000 image to SCUNet and 24 rows and columns of replicated content are silently invented, processed, and cropped away. None of this appears in any of the four papers. It is exactly the class of fact the brief means by *practical deployment realities*, and it is only visible by reading `forward`.",
    cite="measured — verbatim from the four repositories at the commits on slide 59",
    notes="A favourite because it is concrete, verifiable, and invisible from the literature. Good answer to 'what did you learn from the code that you could not learn from the papers?'"))

S.append(dict(t="table", era="meta", part="VI", kicker="70 · What we measured",
    title="Seven architectures, instantiated and timed",
    lead="Each model was instantiated from its own repository at the commit on slide 59, in the configuration that repository uses for denoising. Parameters are `sum(p.numel() for p in model.parameters())`. Latency is the mean of three forward passes at 256×256 after one warm-up, under `torch.no_grad()`, **CPU only**, PyTorch 2.13.0, no CUDA.",
    body={"cols": ["Model", "Configuration", "Parameters", "CPU latency, 256²"],
          "align": "llrr",
          "rows": [
            ["DnCNN-B", "`DnCNN(in_nc=1, nc=64, nb=20)`", "0.668 M", "1.015 s"],
            ["P2N+ backbone, SPI **off**", "`UNet_n2n_un(conv_type='plain')`", "0.991 M", "0.286 s"],
            ["P2N+ backbone, SPI **on**", "`UNet_n2n_un(conv_type='SPI')`", "0.925 M", "0.710 s"],
            ["SCUNet", "`SCUNet(in_nc=3, config=[2]*7, dim=64)`", "9.663 M", "1.685 s"],
            ["Restormer", "paper defaults, `dim=48`, `[4,6,6,8]`", "26.127 M", "10.436 s"],
            ["NAFNet", "SIDD `width=64`, enc `[2,2,4,8]`, mid 12", "115.983 M", "1.899 s"],
            ["MambaIR", "—", "*not measurable*", "import fails"],
          ],
          "hl": [4, 5, 6]},
    foot="**Two caveats, stated before they are asked.** (1) Absolute CPU latencies are **not** comparable to published GPU timings — the *ratios* are the informative quantity. (2) The forward passes used **random tensors**, so no PSNR or SSIM was measured here; every quality number in this deck comes from the papers, and every timing and parameter count on this slide comes from us. The two are never mixed in one column.",
    cite="measured — Stage 2 benchmark, CPU-only container, PyTorch 2.13.0",
    notes="Declaring the random-tensor caveat unprompted is important. The obvious attack is 'did you verify the PSNRs yourself?' — the answer is no, and saying so first is much stronger than conceding it."))

S.append(dict(t="cards", era="meta", part="VI", kicker="71 · What the measurements say",
    title="Four conclusions, none of them visible from a paper",
    lead="These are the readings that justify having run the code at all. Each contradicts something a reader would reasonably assume from the published tables.",
    body={"cards": [
        {"tag": "a", "h": "Parameters do not predict latency", "p": "NAFNet carries **4.4× Restormer's parameters and runs 5.5× faster** on identical hardware. NAFNet is 1×1 and depth-wise convolutions on fast GEMM paths; Restormer's `rearrange` calls force layout changes and its attention matmuls are poorly served by a CPU backend. **'More efficient' is meaningless without naming the metric — parameters, MACs, or wall-clock — and the device.**"},
        {"tag": "b", "h": "SPI costs latency, not parameters", "p": "Switching Symmetric Prior Injection on **reduces** P2N+'s parameters by 6.7% (0.991 M → 0.925 M), because `Symlayer` routes through a half-width bottleneck — yet latency rises **2.5×** (0.286 s → 0.710 s), because every layer is evaluated twice, on x and on −x. This is the exact opposite of what a parameter table predicts, and it is invisible unless you run it."},
        {"tag": "c", "h": "The oldest model is the smallest and still not the fastest", "p": "DnCNN is the smallest model in the table at 0.668 M and is nonetheless **slower than the 0.991 M P2N+ backbone**, because DnCNN is 20 sequential full-resolution 3×3 convolutions at 64 channels while a U-Net does most of its work at reduced resolution. Depth at full resolution is expensive in a way parameter count does not show."},
        {"tag": "d", "h": "Some models simply do not run", "p": "MambaIR raises `ModuleNotFoundError: mamba_ssm` without compiled CUDA extensions. That is not a gap in our experiment — it *is* the result. A model that cannot be imported on a CPU machine has a deployment profile fundamentally different from one that can, and no paper reports this. The repository's own changelog also records that published complexity figures computed with `thop` were wrong."},
    ]},
    cite="measured — Stage 2 benchmark · MambaIR repository changelog",
    notes="Reading (a) is the one to lead with. It is a clean, falsifiable, counterintuitive claim backed by a number you produced, which is exactly what the brief's Practical Integration criterion rewards."))
