# -*- coding: utf-8 -*-
"""
Six slides inserted into the master deck after slide 89.

They close the gaps the evolution/SOTA review identified: explicit SOTA
qualification with benchmark and window, an answer to "why several SOTAs",
consolidated Before -> After implementation tables, and grounded proposals.
"""
NEW = [

dict(t="table", era="meta", part="VII", kicker="SOTA, qualified",
    title="Four current methods — each leads a different benchmark",
    lead="A state-of-the-art claim is only checkable with three things attached: the benchmark and metric, the years it held, and what distinguishes it from the others leading elsewhere. This table supplies all three for every method still current.",
    body={"cols": ["Method", "Leads on", "Figure", "SOTA window", "What distinguishes it", "Cost [measured]"],
          "align": "llllll",
          "rows": [
            ["**NAFNet** (2022)", "SIDD — real sensor noise", "**40.30 dB**", "2022 →", "No attention and no activation functions at all; by far the simplest code", "116.0 M · 1.90 s CPU"],
            ["**Restormer** (2022)", "Urban100 — long-range structure", "**28.33 dB** σ=50", "2022 →", "First past 40 dB on **both** SIDD and DND; channel attention at linear cost", "26.1 M · 10.44 s CPU"],
            ["**MambaIR** (2024)", "DND — held-out real noise", "**40.04 dB**", "2024 →", "Global receptive field at linear cost via a selective state-space scan", "will not import without CUDA"],
            ["**SCUNet** (2023)", "Robustness to *unseen* degradation", "—", "2023 →", "Competes on the **training distribution** rather than the architecture", "**9.7 M** · 1.69 s CPU"],
            ["DnCNN (2017)", "*Historical* — BSD68 Gaussian", "29.23 dB", "2017 – 2021", "The reference line the whole modern field was built against", "0.67 M · 1.02 s CPU"],
            ["BM3D (2007)", "*Zero-shot* — no training data", "28.57 dB", "2007 – 2014", "Still the fallback when there is neither training data nor a GPU", "no training · 2.85 s"],
          ],
          "hl": [0, 1]},
    foot="**Read the second column, not the third.** These methods are not ranked against each other on one axis — they lead *different benchmarks*, and those benchmarks measure *different capabilities*. Windows are stated as the period each held the position on its own benchmark, not as a claim of overall superiority.",
    cite="NAFNet22 abstract · Restormer22 Tables 4, 6 · MambaIR24 Table 6 · DnCNN17 Table II · measured, Stage 2",
    notes="The single most useful slide for a SOTA question. Walk the 'Leads on' column and then deliver the foot. Windows are ours, inferred from publication dates and from which method holds each table — say so if pressed."),

dict(t="cards", era="meta", part="VII", kicker="Why several SOTAs",
    title="Four reasons the field has not converged on one method",
    lead="Newer does not automatically mean universally better, and the reasons are structural rather than a failure of the field to make up its mind. Each of these is measurable.",
    body={"cards": [
        {"tag": "Reason 1", "h": "The benchmarks measure different capabilities",
         "p": "BSD68 measures average-case Gaussian removal and **has saturated** — 0.36 dB across five years. Urban100 measures long-range self-similarity, where the same five years bought 1.98 dB. SIDD and DND measure real sensor noise, where they bought sixteen decibels. Leading one and trailing another is not a contradiction."},
        {"tag": "Reason 2", "h": "The cost axes disagree with each other",
         "p": "Our own measurements give **three incompatible rankings** of the same models. By parameters DnCNN wins; by CPU wall-clock the P2N backbone wins; by real-noise quality NAFNet wins — with 4.4× Restormer's parameters and 5.5× its speed. 'More efficient' is meaningless without naming the metric *and* the device."},
        {"tag": "Reason 3", "h": "Deployment constraints are not quality constraints",
         "p": "MambaIR leads DND by 0.01 dB and **cannot be imported without compiled CUDA extensions**. SCUNet leads no AWGN table and is a third of Restormer's size. Which model is 'best' depends on what you are shipping onto which hardware, and no benchmark captures that."},
        {"tag": "Reason 4", "h": "Supervision availability partitions the field",
         "p": "The two branches answer different questions. Where clean pairs exist, supervision wins by 1.35 dB on BSD68. Where they do not — cryo-TEM, fluorescence microscopy — the self-supervised methods are not *worse*, they are the **only** option, and the supervised leader is simply unavailable."},
    ]},
    foot="**The defensible one-sentence answer:** there is no single best denoiser because 'best' is only defined relative to a benchmark, a cost metric and a supervision regime, and the current leaders differ on all three.",
    cite="Restormer22 Table 4 · NAFNet22 · MambaIR24 · N2V19 §4.1 · measured, Stage 2",
    notes="Expect this question verbatim. Four reasons, each with a number. If time is short, give reason 1 and reason 4 — they are the structural ones."),

dict(t="table", era="meta", part="VII", kicker="Before → after, part 1",
    title="Every step, as an implementation change",
    lead="The same evolution read through the code rather than the papers. Each row names the smallest change that carries the innovation — the connection from contribution, through algorithmic change, to implementation change, to measured improvement.",
    body={"cols": ["Step", "Before", "After", "The change in code", "Measured effect"],
          "align": "lllll",
          "rows": [
            ["BM3D → WNNM (2014)", "Shrink a 3-D transform of the patch group", "Recover a low-rank matrix from it", "Transform call becomes an **iterated SVD with per-singular-value weights**", "+0.26 dB · **271× slower**"],
            ["WNNM → TNRD (2016)", "`while` loop to a tolerance, one fixed rule", "Fixed K stages, each with its own learned filters", "Loop becomes a **fixed stack trained by back-propagation**", "+0.09 dB · 773 s → 0.032 s"],
            ["TNRD → DnCNN (2017)", "Stages derived from a diffusion PDE", "Plain Conv-BN-ReLU ×17, no pooling", "`return self.model(x)` becomes **`return x - self.model(x)`**", "+0.31 dB · one blind model"],
            ["DnCNN → N2N (2018)", "`target = clean`", "`target = second_noisy_shot`", "**One assignment.** Network, optimiser, schedule unchanged", "−0.02 dB · clean data no longer needed"],
            ["N2N → N2V (2019)", "Two noisy shots of one scene", "One noisy image", "**Replace the centre pixel with a random neighbour**; score the loss only there", "−1.15 dB · applicable where no pair exists"],
          ]},
    foot="**Read the fourth column down the page.** An iterated SVD, then a training loop, then eight characters, then one assignment, then a masking trick. The size of the code change is uncorrelated with the size of the conceptual change — which is why reading the repositories was worth doing.",
    cite="DnCNN17 Tables II, IV · N2N18 Table 1 · N2V19 Fig. 4 · code measured at the commits on slide 65",
    notes="The brief asks for contribution → algorithmic change → implementation change → improvement as one chain. This table is that chain, five times."),

dict(t="table", era="meta", part="VII", kicker="Before → after, part 2",
    title="The architecture branch, as an implementation change",
    lead="The same treatment for the three operators that answer bottleneck 3, plus the one method that answers it from the data side instead.",
    body={"cols": ["Step", "Before", "After", "The change in code", "Measured effect"],
          "align": "lllll",
          "rows": [
            ["Spatial → **Restormer** (2022)", "Attention over HW×HW pixels — 4.3×10⁹ entries at 256²", "Attention over C×C channels — 48×48 at level 1", "One einops pattern: `'b (head c) h w -> b head c (h w)'` puts **pixels on the last axis**", "Linear in pixels · +1.98 dB on Urban100 vs DnCNN"],
            ["Attention → **NAFNet** (2022)", "GELU, then a gate; CA with ReLU and Sigmoid", "The gate *is* the nonlinearity", "`x1, x2 = x.chunk(2, dim=1); return x1 * x2`", "+0.08 dB over GELU · 40.30 dB SIDD"],
            ["Attention → **MambaIR** (2024)", "Quadratic attention, or windows that surrender globality", "Selective state-space recurrence", "Flatten to a sequence, **four-directional scan**, plus a local conv and channel attention", "Linear cost · best DND at 40.04 dB"],
            ["Architecture → **SCUNet** (2023)", "Train on AWGN, test on AWGN", "Train on a synthesised degradation pipeline", "The **dataloader** becomes the contribution: Poisson, speckle, JPEG, ISP-simulated sensor noise, resizing", "9.7 M params · robust to unseen degradation"],
          ]},
    foot="**And the honest footnote from NAFNet's own ablation:** the largest single gain in its table is not an architectural component at all — it is **LayerNorm, +0.44 dB**, because it stabilises training at a ten-times larger learning rate. A substantial share of reported architectural progress in restoration is optimisation progress wearing a costume.",
    cite="Restormer22 §3.1, Tables 4, 7 · NAFNet22 §4, §5 · MambaIR24 §3.2 · SCUNet23 §3.2 · code measured",
    notes="The LayerNorm footnote is the most intellectually honest line in Part VII. Volunteer it — it demonstrates you read the ablation rather than the abstract."),

dict(t="table", era="meta", part="VIII", kicker="Proposal directions",
    title="Four research directions the limitations actually justify",
    lead="Each is tied to a specific documented gap — from the papers' own words or from our measurements — and each states what would change and how it would be measured. None claims a paper achieved something it did not.",
    body={"cols": ["Direction", "Grounded in", "What would change", "How you would measure it"],
          "align": "llll",
          "rows": [
            ["**Cross the fork** — self-supervised supervision on a modern backbone",
             "Our own finding: no published work trains a Transformer or SSM backbone under RDC/DCS supervision; P2N still ships the 2018 U-Net verbatim",
             "Replace `UNet_n2n_un` with a Restormer or NAFNet block under P2N's RDC/DCS training signal",
             "N2V's own protocol on BSD68 σ=25 and on the cryo-TEM / CTC sets — does the 1.35 dB self-supervision gap shrink?"],
            ["**A cross-ISP generalisation benchmark**",
             "SCUNet's abstract: a general-purpose blind real denoiser *remains unsolved*, and no benchmark evaluates an unseen camera",
             "Train on SIDD, evaluate on DND *and* on a held-out camera; report the drop as the headline number",
             "Δ PSNR between seen and unseen ISP — a quantity nobody currently reports"],
            ["**A perceptual objective that does not surrender fidelity**",
             "Noise2Noise names L2's *spatial blurriness*; perceptual losses are standard in super-resolution and essentially absent from denoising",
             "Add an LPIPS or no-reference term to NAFNet's PSNR loss and report both axes rather than one",
             "PSNR *and* LPIPS jointly on SIDD — accept a small dB loss for a measured perceptual gain"],
            ["**An efficiency protocol the field can agree on**",
             "Three incompatible rankings from our own measurements; MambaIR's changelog conceding its published `thop` figures were wrong",
             "Report parameters, MACs *and* wall-clock on a named device, with the counting method stated alongside",
             "Reproduce the table across CPU and GPU; the change in ranking is itself the result"],
          ]},
    foot="**The one we would pursue is the first.** It falls directly out of the structural claim this deck has carried since Part IV — the two branches have never merged — it is cheap to test because both halves already exist as working code, and it has a clear negative result if the gap does not close.",
    cite="reading, grounded in P2N25 · SCUNet23 abstract · N2N18 §2 · MambaIR24 changelog · measured, Stage 2",
    notes="Answers 'can you identify a research direction'. Commit to the first row and have a reason ready. The negative-result clause matters — a proposal that cannot fail is not a proposal."),

dict(t="two", era="meta", part="VIII", kicker="How to present this deck",
    title="The condensed executive summary, and what it leaves out",
    lead="The brief is explicit that a four-hour presentation is impossible: you present a highly condensed executive summary and are questioned on any part of the full deck. This slide states how that summary is cut, so the choice is deliberate rather than improvised.",
    body={"left": {"h": "What the 26-minute summary covers", "bullets": [
        "**The claim, before the evidence** — four eras, three bottlenecks, one fork in 2018.",
        "**One Before → After per era**, each with the implementation change named: the iterated SVD, `return x - n`, the target swap, the einops rearrange, `x1 * x2`.",
        "**The three bottleneck slides**, because they are what make the timeline evidenced rather than chronological.",
        "**The SOTA comparison and why several coexist**, which is the question most likely to be asked.",
        "**Two presenters**, handing over at the bottleneck slide — the seam where one era's debts become the next era's branches.",
    ]},
     "right": {"h": "What it deliberately leaves to the deck", "bullets": [
        "The full classical derivations — MAP, total variation, the WNNM weighting theorem.",
        "The engineering detail of Part VI: padding constants, framework migration, checkpoint loading, the full measured benchmark.",
        "Per-paper training recipes, dataset tables and the complete bibliography.",
        "**These are exactly the parts you will be questioned on**, which is why the rule stands: do not put anything on a slide you cannot personally explain.",
        "The condensed deck and its run sheet are generated from this deck's own content, so the two cannot drift apart.",
    ]},
    },
    foot="**Per the brief:** the deck is the standalone educational artifact and carries the depth; the presentation is a condensed executive summary of it. Both are in this submission, and the summary's backup index maps every anticipated question to a slide number in this deck.",
    cite="brief §9, TA Presentation 3 — format and deliverable",
    notes="Put this slide where the TA will see it early if they browse. It shows the presentation strategy was designed, not improvised."),
]
