# -*- coding: utf-8 -*-
"""Presentation deck content, part B — Presenter 2."""
S = []

S.append(dict(t="cards", era="meta", part="", kicker="Handover · presenter 2",
    title="2018: the field forks, and never merges",
    lead="Two debts, two communities, two independent answers. Neither branch has adopted the other's advance — which is itself one of the findings of this project, and the source of the open problem we end on.",
    body={"cards": [
        {"tag": "Branch A · bottleneck 2", "h": "Change what the network is *shown*",
         "p": "Noise2Noise → Noise2Void → ZS-N2N → P2N. The architecture stays almost exactly where DnCNN left it; what moves is the **training target**. Each paper removes one more requirement until nothing is needed but the noisy image itself."},
        {"tag": "Branch B · bottleneck 3", "h": "Change what the network *is*",
         "p": "Restormer, NAFNet, SCUNet, MambaIR. Supervision stays exactly as DnCNN had it — paired data, same loss family. What moves is the **operator** that replaces the 3×3 convolution."},
        {"tag": "The evidence they never merged", "h": "P2N ships the 2018 network",
         "p": "In the official P2N repository the class is literally named **`UNet_n2n_un`**, with the 2018 Noise2Noise channel widths. Seven years, and the backbone is unchanged. `[measured]`"},
        {"tag": "The open question", "h": "Nobody has combined them",
         "p": "As far as we found, **no published work trains a Transformer or state-space backbone under self-supervised RDC/DCS supervision.** We return to this as a concrete proposal on slide 40."},
    ]},
    cite="reading — the structural claim of this project · repository: Li-Tong-621/P2N-plus [measured]",
    notes="60s. Presenter 2 opens here. This slide is the map for the next twelve minutes — deliver it with energy, it re-engages the room after the handover."))

# ─────────────── BRANCH A ───────────────
S.append(dict(t="section", era="data", part="3", kicker="Branch A · 2018 – 2025",
    title="Removing the Clean Image",
    lead="Four papers, each removing exactly one requirement its predecessor could not drop.",
    body={"items": ["Noise2Noise — the statistical result",
                    "Noise2Void — the blind spot",
                    "ZS-N2N and P2N — down to one image",
                    "What self-supervision costs"]},
    cite="brief §4", notes="10s."))

S.append(dict(t="code", era="data", part="3", kicker="Noise2Noise · 2018 · before → after",
    title="A theorem worth one conditional",
    lead="Lehtinen et al., ICML 2018. The most striking ratio in this story: a substantial statistical result whose implementation change is a single branch on which tensor becomes the target.",
    body={"lang": "python", "file": "the change, in essence",
     "lines": [
        "# BEFORE — supervised (DnCNN, 2017)",
        "target = clean                      # requires ground truth",
        "loss   = mse(net(noisy), target)",
        "",
        "# AFTER — Noise2Noise (2018)",
        "target = second_noisy_shot          # ← the entire change",
        "loss   = mse(net(noisy), target)",
        "",
        "# network, optimiser, schedule, loss family: all unchanged",
     ],
     "bullets": [
        "**Why it works.** L2 regression learns the *conditional mean* of the target. The paper states the consequence as a triviality: *on expectation, the estimate remains unchanged if we replace the targets with random numbers whose expectations match the targets.*",
        "**So a second noisy photograph of the same scene is a valid target**, because the noise is zero-mean. Given infinite data the solution is *identical* to clean-target training; for finite data the extra variance shrinks with dataset size.",
        "**What it does NOT need:** no likelihood model of the corruption, no density model of clean images.",
        "**Measured cost: 0.02 dB.** Kodak/BSD300/Set14 at σ=25 — clean targets 31.63, noisy targets 31.61. The clean-data requirement was never actually necessary. `[N2N18 Table 1]`",
     ]},
    cite="N2N18 §2, Eq. (2)–(6), Table 1",
    notes="85s. The 0.02 dB number is the punchline — say it last and let it sit."))

S.append(dict(t="table", era="data", part="3", kicker="Noise2Void · 2019 · before → after",
    title="N2V vs N2N — removing the second photograph",
    lead="Krull et al., CVPR 2019. Noise2Noise still needs two independent shots of one scene, which rules out anything that moves and every archival image. N2V removes that too — and pays for it.",
    body={"cols": ["Aspect", "Noise2Noise (2018)", "Noise2Void (2019)", "Why it matters"],
          "align": "llll",
          "rows": [
            ["Requires", "Two noisy shots per scene", "**One noisy image. That is all.**", "Applicable to any archive, any moving subject, any single acquisition"],
            ["Key innovation", "Corrupted target with matching mean", "**Blind-spot receptive field**", "Prediction for pixel i uses its neighbourhood *except pixel i*"],
            ["Why it cannot cheat", "Target is independent of input", "Noise is conditionally pixel-wise independent, so neighbours **carry no information about nᵢ**", "The identity solution becomes unreachable by construction"],
            ["Implementation change", "Swap the target tensor", "**Replace the centre pixel with a random neighbour; score the loss only there**", "A masking trick, not an architecture — any standard CNN acquires the property"],
            ["Performance (BSD68 σ=25)", "28.86 dB", "**27.71 dB**", "−1.15 dB, and 0.88 dB *below* BM3D — the cost is real and the paper does not hide it"],
            ["Applications", "Burst photography, rendering", "**Cryo-TEM, fluorescence microscopy, cell tracking**", "Domains where the paper's own figure captions the ground truth column *does not exist*"],
          ],
          "hl": [4, 5]},
    foot="**The honest framing, and the one to use if challenged.** Self-supervision is not a quality technique, it is an *availability* technique. Where clean data exists, supervision wins by 1.35 dB. Where it does not, the comparison is not 27.71 against 29.23 — it is 27.71 against **nothing at all**.",
    cite="N2V19 §3.1, §3.4, §3.5, §4.1, Fig. 4 · N2N18 Table 1",
    notes="90s. Volunteering the 'worse than BM3D' row before anyone asks is a rigour move. It also sets up the availability argument as your own point rather than a concession."))

S.append(dict(t="table", era="data", part="3", kicker="ZS-N2N · 2023 · P2N · 2025",
    title="Down to one image, then down to no sacrifice",
    lead="The branch finishes by removing the last two requirements. Compressed into one slide because the pattern is now familiar — each paper removes exactly one thing.",
    body={"cols": ["", "ZS-N2N (2023)", "P2N (2025)"],
          "align": "lll",
          "rows": [
            ["Requirement removed", "The **training set**. No corpus, no pretraining.", "The **information loss** itself."],
            ["Key innovation", "A *pair downsampler*: two fixed diagonal filters split one image into a noisy pair with similar signal and independent noise.", "**RDC** — renoise the model's own output with + and −, giving y⁺ and y⁻ at full resolution. **DCS** — train the two denoised results to agree."],
            ["Implementation change", "Two fixed stride-2 convolutions; a **20 000-parameter** two-layer net fitted to that one image; residual + consistency loss.", "**Three forward passes per step**, on tensors that do not exist until the model has run once. Output compared against output, not against a target."],
            ["Why it is not just a new loss", "It is a new *input construction*.", "Same: a loss scores a fixed prediction against a fixed target. P2N changes what goes in, how many passes, and which pair is compared."],
            ["Cost paid", "Half the spatial resolution during training; 1–2 K gradient steps per image.", "Three passes per step; still per-image test-time optimisation."],
            ["Applications", "Single archival images, one-off scientific captures; ~1 min on CPU vs Self2Self's 1.2 h on GPU.", "Self-supervised denoising where masking artefacts are unacceptable."],
          ]},
    foot="**The through-line: the network never moved, the target did.** Clean image (2018) → second copy (2019) → training set (2023) → information loss (2025). Four papers, four requirements removed, one U-Net throughout.",
    cite="ZS-N2N23 §3, §4 · P2N25 (CVPR 2025) · repository measured",
    notes="80s. Do not try to explain both methods fully. Deliver the footnote — it is the takeaway."))

# ─────────────── BRANCH B ───────────────
S.append(dict(t="section", era="arch", part="4", kicker="Branch B · 2021 – 2024",
    title="Replacing the Convolution",
    lead="The other debt: a 35×35 receptive field, and three competing operators that fix it.",
    body={"items": ["The evidence for bottleneck 3",
                    "Restormer — attention on a different axis",
                    "NAFNet — delete the mechanisms",
                    "SCUNet and MambaIR",
                    "Why there are several SOTAs"]},
    cite="brief §4", notes="10s."))

S.append(dict(t="stats", era="arch", part="4", kicker="Bottleneck 3 · the receipt",
    title="One number proves the receptive field is the problem",
    lead="Identical models, identical table, identical noise level. The only thing that changes is the dataset — and the gain changes by a factor of five.",
    body={"stats": [
        {"n": "+0.39 dB", "l": "BSD68, σ=50 · DnCNN → Restormer", "s": "Ordinary natural images, little long-range repetition. Five years of architecture research buys almost nothing."},
        {"n": "+1.98 dB", "l": "Urban100, σ=50 · same two models", "s": "Photographs of buildings — windows and railings repeating across hundreds of pixels. **Five times the gain**, on the dataset made of repetition."},
        {"n": "−0.71 dB", "l": "Barbara, σ=25 · DnCNN vs BM3D, 2017", "s": "The same phenomenon, visible five years earlier in DnCNN's own results, on the one Set12 image dominated by repetitive texture."},
    ],
     "bullets": [
        "**What this proves.** The architecture branch did not make denoising uniformly better. It made denoising better **specifically where non-locality matters** — which is exactly the capability a 3×3 convolution stack structurally lacks.",
        "**Why depth cannot fix it.** Receptive field grows *linearly* with depth: (2d+1)². Reaching WNNM's 361×361 the DnCNN way needs about **180 layers**. The fix had to be a different operator, not more of the same one.",
    ]},
    foot="**Provenance:** the 0.39-versus-1.98 comparison is our own analysis of published values, both taken from Restormer's Table 4 so the protocol is identical. Say *computed from Table 4* if challenged.",
    cite="Restormer22 Table 4 · DnCNN17 Table III, Table I",
    notes="80s. This is the strongest analytical slide in the talk. It is your own reading of published numbers, which is what 'synthesis' means in the grading criteria."))

S.append(dict(t="code", era="arch", part="4", kicker="Restormer · 2022 · before → after",
    title="Attention becomes affordable by changing one axis",
    lead="Zamir et al., CVPR 2022. Standard self-attention costs O(W²H²) — a 256×256 image needs a 4.3-billion-entry attention matrix, against 196 tokens for a ViT. Restormer's innovation is to attend over **channels** instead of pixels.",
    body={"lang": "python", "file": "Restormer/basicsr/models/archs/restormer_arch.py — Attention.forward",
     "lines": [
        "# BEFORE — spatial attention (ViT / SwinIR)",
        "#   'b c h w -> b head (h w) c'      -> q@kT is (HW x HW)",
        "#   256x256  ->  65,536 x 65,536",
        "",
        "# AFTER — Restormer MDTA",
        "q = rearrange(q,'b (head c) h w -> b head c (h w)',",
        "              head=self.num_heads)   # ← pixels on the LAST axis",
        "k = rearrange(k, ...); v = rearrange(v, ...)",
        "q = F.normalize(q,dim=-1); k = F.normalize(k,dim=-1)",
        "attn = (q @ k.transpose(-2,-1)) * self.temperature",
        "#   -> (C/head x C/head).  At level 1: 48 x 48, any image size",
     ],
     "bullets": [
        "**One einops pattern is the entire complexity claim.** Putting pixels on the last axis makes `q @ k.transpose(-2,-1)` a C×C matrix — 48×48 whether the image is 256² or 4000×3000. Cost becomes **linear** in pixels.",
        "**Is it really global?** Honestly: not pairwise-pixel. Every channel is computed from every pixel, so channel statistics carry image-wide information; the paper says global relationships are *implicitly* modelled and never claims otherwise.",
        "**The depth-wise convolutions are load-bearing, not decoration.** Removing `qkv_dwconv` costs 0.15 dB on Urban100 σ=50 — more than most architecture papers gain in total. `[Restormer22 Table 7]`",
        "**Why SOTA:** first method past **40 dB on both SIDD and DND**; leads Urban100 at every noise level; 3.14× fewer FLOPs and 13× faster than SwinIR. Window: **2022 →**, still leading Urban100 and DND-adjacent tables.",
     ]},
    cite="measured — swz30/Restormer, verbatim · Restormer22 §1, §3.1, Tables 4, 6, 7",
    notes="95s. 'Show me where the attention is actually linear' is the single most likely code question in the defence. Point at the rearrange."))

S.append(dict(t="code", era="arch", part="4", kicker="NAFNet · 2022 · before → after",
    title="The paper that asked whether any of it was necessary",
    lead="Chen et al., ECCV 2022. While everyone added mechanisms, NAFNet removed them and scored higher. Its derivation is the most elegant reasoning in the modern half of this story.",
    body={"lang": "python", "file": "NAFNet/basicsr/models/archs/NAFNet_arch.py",
     "lines": [
        "# BEFORE — GELU, then a gate",
        "#   GELU(x) = 0.5x(1+tanh[sqrt(2/pi)(x+0.044715x^3)])",
        "#   CA(X)   = X * sigmoid(W2 relu(W1 pool(X)))",
        "",
        "# AFTER — SimpleGate: the gate IS the nonlinearity",
        "def forward(self, x):",
        "    x1, x2 = x.chunk(2, dim=1)",
        "    return x1 * x2                # ← replaces GELU entirely",
        "",
        "# AFTER — SCA: no sigmoid, no relu",
        "self.sca = nn.Sequential(nn.AdaptiveAvgPool2d(1),",
        "                         nn.Conv2d(c, c, 1))",
     ],
     "bullets": [
        "**The derivation.** GELU is a *special case* of a gated linear unit with f, g = identity and σ = Φ. But a GLU *itself contains nonlinearity and does not depend on σ* — f(X)⊙g(X) is nonlinear because a product of two linear maps is not linear. So delete the activation; the gate already supplies it.",
        "**Apply the same argument to channel attention** and both its nonlinearities vanish too. Result: **no Sigmoid, no ReLU, no GELU, no Softmax anywhere** — *the first work demonstrating that the nonlinear activation functions may not be necessary for SOTA computer vision methods.*",
        "**Both simplifications improved the score.** SimpleGate beats GELU (+0.08), SCA beats CA (+0.03) on SIDD.",
        "**The uncomfortable finding in their own ablation:** the largest single gain is **LayerNorm, +0.44 dB** — because it stabilises training at a 10× larger learning rate. *A large share of reported architectural progress in restoration is optimisation progress wearing a costume.*",
     ]},
    foot="**Why SOTA: 40.30 dB on SIDD — the highest real-noise result in our comparison — at less than half the previous best's compute.** Window: **2022 →**, still the leader on SIDD. And by far the simplest code to maintain.",
    cite="measured — megvii-research/NAFNet, verbatim · NAFNet22 §4, §5, abstract",
    notes="95s. The LayerNorm finding is the intellectually honest highlight of the whole talk. Do not skip it."))

S.append(dict(t="table", era="arch", part="4", kicker="SCUNet · 2023 · MambaIR · 2024",
    title="Two more answers — one architectural, one not about architecture at all",
    lead="The branch does not end with Transformers. MambaIR proposes a different operator again; SCUNet argues the operator was never the problem.",
    body={"cols": ["", "MambaIR (2024)", "SCUNet (2023)"],
          "align": "lll",
          "rows": [
            ["The claim", "Attention is quadratic; windowing surrenders globality. Borrow a **selective state-space model** — global receptive field at **linear** cost.", "**The benchmark is the problem.** A model trained on AWGN *performs poorly for most of real images due to noise assumption mismatch*."],
            ["Technical change", "S6 recurrence with **input-dependent** B, C, Δ. Dual form: recurrent (unbounded memory) for reach, convolutional for parallel training.", "Keep local *and* non-local priors **in parallel** — split the feature map, half to a Swin block, half to a residual conv block."],
            ["Implementation change", "Flatten the image to a sequence; **four-directional scan**; add a local conv (fixes *local pixel forgetting*) and channel attention (fixes redundancy).", "The **dataloader** becomes the contribution: Gaussian, Poisson, speckle, JPEG, and **sensor noise synthesised through a real inverted ISP**, plus resizing and double degradation."],
            ["Why SOTA / where", "**Best DND result, 40.04 dB** — by 0.01 dB. Leads super-resolution on Manga109 ×2 by 0.41 dB over SwinIR.", "Not top of any AWGN table — and does not need to be. **9.663 M parameters**, smallest of the four, built to survive real photographs."],
            ["Cost / limitation", "**Will not import without compiled CUDA extensions.** Its own changelog records that published `thop` complexity figures were wrong. `[measured]`", "Its abstract still concedes a general-purpose blind real denoiser **remains unsolved**."],
          ]},
    cite="MambaIR24 §3.1, §3.2, Tables 1, 2, 6 · SCUNet23 abstract, §1, §3.1, §3.2 · measured",
    notes="75s. The MambaIR import failure is a genuine deployment result nobody reports — worth mentioning, it shows you ran the code."))

# ─────────────── SOTA SYNTHESIS ───────────────
S.append(dict(t="section", era="meta", part="5", kicker="Synthesis",
    title="Why There Is No Single Winner",
    lead="The question this talk was built to answer, now with the numbers behind it.",
    body={"items": ["The SOTA comparison table",
                    "Why several coexist",
                    "Applications and trade-offs",
                    "Open problems and proposals"]},
    cite="brief §6", notes="8s."))

S.append(dict(t="table", era="meta", part="5", kicker="SOTA comparison",
    title="Four current methods — each leads a different table",
    lead="Every row names the benchmark, the metric and the window, because a SOTA claim without those is not checkable. All quality figures are reproduced from published tables; parameters and CPU latency are our own measurements.",
    body={"cols": ["Method", "Leads on", "Figure", "SOTA window", "What distinguishes it", "Cost"],
          "align": "llllll",
          "rows": [
            ["**NAFNet** (2022)", "SIDD — real sensor noise", "**40.30 dB**", "2022 →", "No attention, no activation functions at all; simplest code", "116.0 M params · 1.90 s CPU"],
            ["**Restormer** (2022)", "Urban100 — long-range structure", "**28.33 dB** σ=50", "2022 →", "First past 40 dB on **both** SIDD and DND; channel attention at linear cost", "26.1 M · **10.44 s CPU**"],
            ["**MambaIR** (2024)", "DND — held-out real noise", "**40.04 dB**", "2024 →", "Global receptive field at linear cost via selective state-space scan", "Needs compiled CUDA to import"],
            ["**SCUNet** (2023)", "Robustness to *unseen* degradation", "—", "2023 →", "Competes on the **training distribution**, not the architecture", "**9.7 M** · 1.69 s CPU"],
            ["DnCNN (2017)", "*Historical* — BSD68 Gaussian", "29.23 dB", "2017 – 2021", "The reference the whole field was built against", "0.67 M · 1.02 s CPU"],
            ["BM3D (2007)", "*Zero-shot* — no training data", "28.57 dB", "2007 – 2014", "Still the fallback when there is no data and no GPU", "No training · 2.85 s"],
          ],
          "hl": [0, 1]},
    foot="**Read the second column, not the third.** These methods are not ranked against each other on one axis — they lead *different benchmarks*, and those benchmarks measure *different capabilities*. That is the whole answer to 'why several SOTAs'.",
    cite="NAFNet22 abstract · Restormer22 Tables 4, 6 · MambaIR24 Table 6 · DnCNN17 Table II · measured [Stage 2]",
    notes="100s. The centrepiece of the synthesis. Walk the second column, then deliver the footnote."))

S.append(dict(t="cards", era="meta", part="5", kicker="Why several SOTAs",
    title="Four reasons the field has not converged on one method",
    lead="This is the question the professor is most likely to ask, so it gets its own slide rather than a sentence.",
    body={"cards": [
        {"tag": "Reason 1", "h": "The benchmarks measure different things",
         "p": "BSD68 measures average-case Gaussian removal and **has saturated** — 0.36 dB across five years. Urban100 measures long-range self-similarity. SIDD and DND measure real sensor noise. A method can lead one and trail another without any contradiction."},
        {"tag": "Reason 2", "h": "The cost axes disagree with each other",
         "p": "Our own measurements give **three incompatible rankings** of the same models: by parameters DnCNN wins; by CPU wall-clock the P2N backbone wins; by real-noise quality NAFNet wins. NAFNet has 4.4× Restormer's parameters and runs **5.5× faster**. 'More efficient' is meaningless without naming the metric and the device."},
        {"tag": "Reason 3", "h": "Deployment constraints are not quality constraints",
         "p": "MambaIR leads DND by 0.01 dB and **cannot be imported without compiled CUDA extensions**. SCUNet leads nothing and is a third of Restormer's size. Which one is 'best' depends entirely on what you are shipping onto what hardware."},
        {"tag": "Reason 4", "h": "Supervision availability partitions the field",
         "p": "Branch A and branch B answer different questions. Where clean pairs exist, supervision wins by 1.35 dB. Where they do not, the self-supervised methods are not *worse* — they are the **only** option, and the supervised SOTA is simply unavailable."},
    ]},
    cite="Restormer22 Table 4 · NAFNet22 · MambaIR24 · N2V19 §4.1 · measured",
    notes="85s. If you only have time for one slide in this section, it is this one. It demonstrates understanding rather than knowledge."))

S.append(dict(t="table", era="meta", part="5", kicker="Applications and trade-offs",
    title="What you would actually deploy, and why",
    lead="The honest answer to 'which is best' names the constraint first. Five constraints, five different answers, all current — which is what an unresolved research question looks like when you have to ship something.",
    body={"cols": ["If your constraint is…", "Deploy", "Because", "Accept"],
          "align": "llll",
          "rows": [
            ["Real photos, GPU, paired data", "**NAFNet**", "40.30 dB on SIDD; best accuracy-per-millisecond we measured; simplest code to maintain", "116 M parameters"],
            ["Repetitive structure, max quality", "**Restormer**", "Leads Urban100 at every σ; only method past 40 dB on both real-noise benchmarks", "10.4 s per 256² on CPU"],
            ["CPU or memory bound", "**SCUNet**", "9.7 M parameters; synthetic-degradation training survives resized and JPEG'd input", "Not top of any AWGN table"],
            ["No clean data exists at all", "**P2N** / **ZS-N2N**", "Microscopy, cryo-EM, astronomy — where ground truth cannot be acquired", "Per-image test-time optimisation"],
            ["No data, no GPU, no dependencies", "**BM3D**", "Seventeen years old and still beats AWGN-trained DnCNN on real noise by 1.99 dB", "2.85 s, and a quality ceiling"],
          ]},
    foot="**Denoising is rarely the product.** It is preprocessing for detection and segmentation, a plug-and-play prior inside deblurring and super-resolution solvers, and — per DnCNN-3 — a *template*: redefine v and the same network does super-resolution and JPEG deblocking. `[SCUNet23 §1 · DnCNN17 §III-D]`",
    cite="NAFNet22 · Restormer22 · SCUNet23 · P2N25 · ZS-N2N23 · measured",
    notes="75s. Never answer 'which would you use' with a single name. Answer with the constraint that decides."))

S.append(dict(t="cards", era="meta", part="5", kicker="Open problems",
    title="What eighteen years did not solve",
    lead="Each of these is grounded in a documented limitation from the papers themselves or in our own measurements — not speculation.",
    body={"cards": [
        {"tag": "Open 1", "h": "A blind denoiser for real cameras",
         "p": "SCUNet's abstract states it *remains unsolved*. Neither synthetic degradation nor SIDD-trained models generalise to an **unseen camera with an unseen ISP**, and no benchmark currently measures that. DnCNN scores **23.66 dB** on SIDD — a 16 dB collapse, not a graceful degradation."},
        {"tag": "Open 2", "h": "Fidelity metrics reward blur",
         "p": "Every loss in the modern field is L1, L2 or PSNR, and all three recover a **conditional mean** — which is smoother than any plausible clean image. Noise2Noise names the mechanism itself: L2 training *results in spatial blurriness*. While leaderboards rank by PSNR, the incentive points the wrong way."},
        {"tag": "Open 3", "h": "Nobody agrees what 'efficient' means",
         "p": "Three incompatible rankings from our own measurements, and MambaIR's changelog concedes its published complexity figures were wrong. Efficiency claims across papers are close to uncheckable."},
        {"tag": "Open 4", "h": "The benchmarks have saturated",
         "p": "BSD68 σ=25 moved **0.36 dB in five years** while Urban100 moved five times as much and SIDD moved sixteen decibels. A benchmark that cannot distinguish 2017 from 2022 is no longer measuring what the field works on."},
    ]},
    cite="SCUNet23 abstract · Restormer22 Tables 4, 6 · N2N18 §2 · measured",
    notes="70s. These four set up the proposals on the next slide — do not linger, the payoff is next."))

S.append(dict(t="table", era="meta", part="5", kicker="Proposal directions",
    title="Four research directions the limitations actually justify",
    lead="Each is tied to a specific documented gap, states what would change, and names how it would be measured. None of these claims a paper achieved something it did not.",
    body={"cols": ["Direction", "Grounded in", "What would change", "How you would measure it"],
          "align": "llll",
          "rows": [
            ["**Cross the fork:** self-supervised supervision on a modern backbone",
             "Our own finding — no published work trains a Transformer or SSM backbone under RDC/DCS supervision; P2N still ships the 2018 U-Net",
             "Replace `UNet_n2n_un` with a Restormer or NAFNet block under P2N's RDC/DCS training signal",
             "N2V's own protocol on BSD68 σ=25 and on the cryo-TEM / CTC sets; does the 1.35 dB self-supervision gap shrink?"],
            ["**Cross-ISP generalisation benchmark**",
             "SCUNet's abstract: a general blind real denoiser *remains unsolved*, and no benchmark tests unseen cameras",
             "Train on SIDD, evaluate on DND *and* a held-out camera; report the drop as the headline number",
             "Δ PSNR between seen and unseen ISP — a metric nobody currently reports"],
            ["**Perceptual objective without losing fidelity**",
             "Noise2Noise names L2's *spatial blurriness*; perceptual losses are common in SR and absent from denoising",
             "Add an LPIPS or no-reference term to NAFNet's PSNR loss and report both axes, not one",
             "PSNR *and* LPIPS jointly on SIDD — accept a small dB loss for a measured perceptual gain"],
            ["**An efficiency protocol the field can agree on**",
             "Three incompatible rankings from our measurements; MambaIR's corrected `thop` figures",
             "Report parameters, MACs *and* wall-clock on a named device, with the counting method stated",
             "Reproduce the table across CPU and GPU; the ratio changes are themselves the result"],
          ]},
    foot="**The first row is the one we would pursue.** It falls directly out of the structural claim of this project — the two branches have never merged — and it is cheap to test, because both halves already exist as working code.",
    cite="reading, grounded in P2N25, SCUNet23 abstract, N2N18 §2, MambaIR24 changelog, and our own measurements",
    notes="90s. This is the slide that answers 'can you identify a proposal'. The footnote commits to one — have a reason ready for why that one."))

S.append(dict(t="quote", era="meta", part="5", kicker="Conclusion",
    title="The evolution, in one paragraph",
    lead="",
    body={"q": "Denoising is the cleanest case study in how computer vision replaced hand-designed priors with learned ones, because here the prior is written down explicitly and you can watch it move.\n\nFour eras, three bottlenecks. Manual prior design ended when DnCNN made the prior a downloadable file. That created two new debts — it needed clean data, and it could only see 35 pixels — and in 2018 the field forked to pay them off separately.\n\nNeither branch has adopted the other's advance. And because three architectures now lead three different benchmarks while none solves real-camera generalisation, the story ends in an open question rather than a winner.",
     "attrib": "What the evidence in this talk supports."},
    cite="reading — the organising claim, carried since Stage 1",
    notes="45s. Deliver from memory, slide behind you. Then stop and invite questions — do not trail off."))

S.append(dict(t="table", era="meta", part="", kicker="Backup · question index",
    title="Where to find the answer to what you are about to be asked",
    lead="Kept for the Q&A. The full evidence for every claim in this talk is in the 100-slide master deck, indexed here by the question likely to prompt it.",
    body={"cols": ["If asked…", "Answer in one line", "Master deck"],
          "align": "lll",
          "rows": [
            ["Why is 0.6 dB a big deal?", "Practical ceiling over BM3D was 0.3 dB, theoretical bound 0.7 dB — DnCNN took 85%", "10, 37"],
            ["Why predict noise, not the image?", "y is closer to x than to v, so learning the image forces an identity mapping — the hard point in parameter space", "33"],
            ["Why do RL and BN need each other?", "RL makes layer inputs Gaussian-like and content-independent — what BN's batch statistics assume", "34"],
            ["Why depth 17?", "RF = (2d+1)² set to 35×35 to match EPLL, the smallest effective patch size in the field", "35"],
            ["How can noisy targets work?", "L2 learns the conditional mean; the mean of a zero-mean corrupted target is the clean target", "43"],
            ["Where is Restormer's attention linear?", "`Attention.forward` — the rearrange puts pixels last, so q@kᵀ is C×C not HW×HW", "69"],
            ["Why is NAFNet faster with more parameters?", "1×1 and depth-wise convs hit optimised GEMM paths; rearrange forces tensor-layout changes", "77"],
            ["What did the code tell you that the papers did not?", "Padding constants differ 8×; SPI cuts parameters and triples latency; MambaIR needs CUDA to import", "75, 77"],
            ["Which would you deploy?", "Name the constraint first — five constraints, five answers, all current", "89"],
            ["Did you verify the PSNRs yourself?", "No. Every quality figure is reproduced from a named published table; only parameters and latency are ours", "81, 93"],
          ]},
    foot="**The rule for the defence:** do not put anything on a slide you cannot personally explain. Every claim in this talk traces to a named table in a named paper, or to a measurement whose method is stated.",
    cite="reading — Q&A index",
    notes="Do not present this slide. Have it open during questions. Print it if you can."))
